# Generated by Django 2.0.6 on 2021-06-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_management', '0004_auto_20180803_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_num', models.CharField(blank=True, max_length=255, null=True)),
                ('sex', models.CharField(blank=True, max_length=1, null=True)),
                ('major', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('train_mode_num', models.IntegerField(blank=True, null=True)),
                ('train_mode', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_code', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_subordinate_code', models.IntegerField(blank=True, null=True)),
                ('unit_subordinate', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_properties_code', models.IntegerField(blank=True, null=True)),
                ('unit_properties', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_location_code', models.IntegerField(blank=True, null=True)),
                ('unit_location', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_address', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_telephone', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_postcode', models.IntegerField(blank=True, null=True)),
                ('file_forward_address', models.CharField(blank=True, max_length=255, null=True)),
                ('breach_contract1', models.CharField(blank=True, max_length=255, null=True)),
                ('breach_contract2', models.CharField(blank=True, max_length=255, null=True)),
                ('education', models.CharField(blank=True, max_length=255, null=True)),
                ('direct_unit', models.CharField(blank=True, max_length=255, null=True)),
                ('origin_location', models.CharField(blank=True, max_length=255, null=True)),
                ('origin_location_code', models.IntegerField(blank=True, null=True)),
                ('sign_flag', models.IntegerField(blank=True, null=True)),
                ('remark1', models.CharField(blank=True, max_length=255, null=True)),
                ('remark2', models.CharField(blank=True, max_length=255, null=True)),
                ('remark3', models.CharField(blank=True, max_length=255, null=True)),
                ('remark4', models.CharField(blank=True, max_length=255, null=True)),
                ('graduate_direction_code', models.CharField(blank=True, max_length=255, null=True)),
                ('graduate_direction', models.CharField(blank=True, max_length=255, null=True)),
                ('is_one_employ', models.IntegerField(blank=True, null=True)),
                ('is_province_employ', models.CharField(blank=True, max_length=255, null=True)),
                ('is_teacher_employ', models.CharField(blank=True, max_length=255, null=True)),
                ('report_certificate', models.IntegerField(blank=True, null=True)),
                ('entrance_department', models.CharField(blank=True, max_length=50, null=True)),
                ('entrance_major', models.CharField(blank=True, max_length=50, null=True)),
                ('school_system', models.IntegerField(blank=True, null=True)),
                ('double_select', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('province_net', models.IntegerField(blank=True, null=True)),
                ('residence', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('unit_type_code', models.IntegerField(blank=True, null=True)),
                ('unit_type', models.CharField(blank=True, max_length=255, null=True)),
                ('address_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'total',
            },
        ),
    ]
